In [1]:
import random

In [23]:
import numpy as np

In [32]:
import statistics as st

In [65]:
from sklearn import linear_model, metrics

In [2]:
random.random()

0.25341569862070523

In [3]:
[random.random() for _ in range(5)]

[0.5014919954296959,
 0.8135228884117683,
 0.8695575682923019,
 0.013628941829058938,
 0.004942654816064818]

In [19]:
seedArray = [random.random() for _ in range(5)]

In [24]:
Y = np.asarray(seedArray)

In [26]:
Y = Y * 2

In [27]:
Y

array([0.7391317 , 0.80129404, 1.12298677, 1.83028935, 0.15818774])

In [16]:
random.gauss(0,0.1)

-0.05288874820228295

In [103]:
def printStats():
    print('Var(Z) = ', st.variance(Z))
    print('Var(X) = ', st.variance(X))
    print('Var(Y) = ', st.variance(Y))
    print('Cov(Z,X) = ', np.cov(Z,X)[0,1])
    print('Cov(Z,Y) = ', np.cov(Z,Y)[0,1])
    print('Cov(X,Y) = ', np.cov(Y,X)[0,1])
    lin_modelXZ = linear_model.LinearRegression()
    lin_modelXZ.fit(Z.reshape(-1,1), X.reshape(-1,1))
    print('Regression coefficient X on Z (gamma)', lin_modelXZ.coef_[0,0], 'Ux = ', lin_modelXZ.intercept_[0]) 
    lin_modelYXZ = linear_model.LinearRegression()
    lin_modelYXZ.fit(np.transpose(np.vstack((X,Z))), Y.reshape(-1,1))
    print('Regression coefficient Y on X and Z: alpha = ', lin_modelYXZ.coef_[0,0], ', beta = ', lin_modelYXZ.coef_[0,1], ', Uy = ', lin_modelYXZ.intercept_)
    print('Corr(Z,X) = ', np.corrcoef(Z,X)[0,1])
    print('Corr(Z,Y) = ', np.corrcoef(Z,Y)[0,1])
    print('Corr(X,Y) = ', np.corrcoef(Y,X)[0,1])

In [126]:
def printStats2():
    print('Var(Z) = ', st.variance(Z))
    print('Var(X) = ', st.variance(X))
    print('Var(Y) = ', st.variance(Y))
    print('Var(W) = ', st.variance(W))
    print('Cov(Z,X) = ', np.cov(Z,X)[0,1])
    print('Cov(Z,Y) = ', np.cov(Z,Y)[0,1])
    print('Cov(X,Y) = ', np.cov(Y,X)[0,1])
    print('Cov(W,Y) = ', np.cov(Y,W)[0,1])
    lin_modelXZ = linear_model.LinearRegression()
    lin_modelXZ.fit(Z.reshape(-1,1), X.reshape(-1,1))
    print('Regression coefficient X on Z (gamma)', lin_modelXZ.coef_[0,0], 'Ux = ', lin_modelXZ.intercept_[0]) 
    lin_modelYZ = linear_model.LinearRegression()
    lin_modelYZ.fit(Z.reshape(-1,1), Y.reshape(-1,1))
    print('Regression coefficient Y on Z: beta = ', lin_modelYZ.coef_[0,0], ', Uy = ', lin_modelYZ.intercept_)
    lin_modelWY = linear_model.LinearRegression()
    lin_modelWY.fit(W.reshape(-1,1), Y.reshape(-1,1))
    print('Regression coefficient Y on W (beta)', lin_modelWY.coef_[0,0], 'Uy = ', lin_modelWY.intercept_[0])
    print('Corr(Z,X) = ', np.corrcoef(Z,X)[0,1])
    print('Corr(Z,Y) = ', np.corrcoef(Z,Y)[0,1])
    print('Corr(X,Y) = ', np.corrcoef(Y,X)[0,1])
    print('Corr(W,Y) = ', np.corrcoef(Y,W)[0,1])

In [117]:
n=10000
alpha = 2
beta = 0.5
gamma = 2
Ux = np.asarray([random.gauss(0,1) for _ in range(n)])
Uz = np.asarray([random.gauss(0,1) for _ in range(n)])
Uy = np.asarray([random.gauss(0,1) for _ in range(n)])

Z = Uz
X = gamma * Z + Ux
Y = alpha * X + beta * Z + Uy

In [118]:
printStats()

Var(Z) =  1.001277674307109
Var(X) =  5.028725925381718
Var(Y) =  25.535245839085476
Cov(Z,X) =  2.0121828766823064
Cov(Z,Y) =  4.541106118847287
Cov(X,Y) =  11.096078063976092
Regression coefficient X on Z (gamma) 2.009615242919255 Ux =  -0.011137591107989675
Regression coefficient Y on X and Z: alpha =  2.0001795896995644 , beta =  0.515720075873778 , Uy =  [0.01172765]
Corr(Z,X) =  0.8967289677240959
Corr(Z,Y) =  0.898078630875765
Corr(X,Y) =  0.9791979567122366


In [102]:
print('Var(Z) = ', st.variance(Z))
print('Var(X) = ', st.variance(X))
print('Var(Y) = ', st.variance(Y))
print('Cov(Z,X) = ', np.cov(Z,X)[0,1])
print('Cov(Z,Y) = ', np.cov(Z,Y)[0,1])
print('Cov(X,Y) = ', np.cov(Y,X)[0,1])
lin_modelXZ = linear_model.LinearRegression()
lin_modelXZ.fit(Z.reshape(-1,1), X.reshape(-1,1))
print('Regression coefficient X on Z (gamma)', lin_modelXZ.coef_[0,0], 'Ux = ', lin_modelXZ.intercept_[0]) 
lin_modelYXZ = linear_model.LinearRegression()
lin_modelYXZ.fit(np.transpose(np.vstack((X,Z))), Y.reshape(-1,1))
print('Regression coefficient Y on X and Z: alpha = ', lin_modelYXZ.coef_[0,0], ', beta = ', lin_modelYXZ.coef_[0,1], ', Uy = ', lin_modelYXZ.intercept_)
print('Corr(Z,X) = ', np.corrcoef(Z,X)[0,1])
print('Corr(Z,Y) = ', np.corrcoef(Z,Y)[0,1])
print('Corr(X,Y) = ', np.corrcoef(Y,X)[0,1])


Var(Z) =  1.0092419610619592
Var(X) =  5.076759793932457
Var(Y) =  25.584156637780815
Cov(Z,X) =  2.028452727924502
Cov(Z,Y) =  4.550388720358701
Cov(X,Y) =  11.162379753326736
Regression coefficient X on Z (gamma) 2.009877518162339 Ux =  -0.0004055582248648146
Regression coefficient Y on X and Z: alpha =  2.0170223401843654 , beta =  0.45475145686980484 , Uy =  [0.00762396]
Corr(Z,X) =  0.8961360200685252
Corr(Z,Y) =  0.8954993935941485
Corr(X,Y) =  0.9794402180019317


In [128]:
n=10000
alpha = 2
beta = 0.5
gamma = 1
Ux = np.asarray([random.gauss(0,1) for _ in range(n)])
Uz = np.asarray([random.gauss(0,1) for _ in range(n)])
Uy = np.asarray([random.gauss(0,1) for _ in range(n)])
Uw = np.asarray([random.gauss(0,1) for _ in range(n)])

Z = alpha * X + Uz
X = Ux
W = gamma * Z + Uw
Y = beta * Z + Uy

In [129]:
printStats2()

Var(Z) =  5.067890888349403
Var(X) =  1.0051959200692604
Var(Y) =  2.198928100306191
Var(W) =  6.103794541194123
Cov(Z,X) =  -0.025881303504756988
Cov(Z,Y) =  2.4802417249700834
Cov(X,Y) =  -0.021827598701739663
Cov(W,Y) =  2.502585779925685
Regression coefficient X on Z (gamma) -0.005106918060184721 Ux =  -0.00606885417866493
Regression coefficient Y on Z: beta =  0.4894031421773346 , Uy =  [0.01377525]
Regression coefficient Y on W (beta) 0.4100049179302954 Uy =  0.009273622196511027
Corr(Z,X) =  -0.011466929940219611
Corr(Z,Y) =  0.7429761395619526
Corr(X,Y) =  -0.014681657468926137
Corr(W,Y) =  0.6830987720947765


In [56]:
np.cov(X,Y)

array([[ 4.16539222,  9.41832741],
       [ 9.41832741, 22.25558065]])

In [46]:
def covariance(x, y):
    # Finding the mean of the series x and y
    mean_x = sum(x)/float(len(x))
    mean_y = sum(y)/float(len(y))
    # Subtracting mean from the individual elements
    sub_x = [i - mean_x for i in x]
    sub_y = [i - mean_y for i in y]
    numerator = sum([sub_x[i]*sub_y[i] for i in range(len(sub_x))])
    denominator = len(x)-1
    cov = numerator/denominator
    return cov

In [97]:
np.cov(X,Z)

array([[5.01778234, 2.0163808 ],
       [2.0163808 , 1.0009665 ]])

In [98]:
np.cov(X,Z)[1,0]

2.016380802743516

In [59]:
covariance(X,Z)

1.8208494461434446

In [55]:
def correlation(x, y):
    # Finding the mean of the series x and y
    mean_x = sum(x)/float(len(x))
    mean_y = sum(y)/float(len(y))
    # Subtracting mean from the individual elements
    sub_x = [i-mean_x for i in x]
    sub_y = [i-mean_y for i in y]
    # covariance for x and y
    numerator = sum([sub_x[i]*sub_y[i] for i in range(len(sub_x))])
    # Standard Deviation of x and y
    std_deviation_x = sum([sub_x[i]**2.0 for i in range(len(sub_x))])
    std_deviation_y = sum([sub_y[i]**2.0 for i in range(len(sub_y))])
    # squaring by 0.5 to find the square root
    denominator = (std_deviation_x*std_deviation_y)**0.5 # short but equivalent to (std_deviation_x**0.5) * (std_deviation_y**0.5)
    cor = numerator/denominator
    return cor

In [60]:
np.corrcoef(X,Z)

array([[1.        , 0.90908713],
       [0.90908713, 1.        ]])

In [62]:
correlation(Z,X)

0.909087130971008

In [84]:
np.transpose(np.vstack((Z,X))).shape

(1000, 2)

In [86]:
lin_model = linear_model.LinearRegression()
lin_model.fit(np.transpose(np.vstack((Z,X))), Y.reshape(-1,1))
print('Coefficients: ', lin_model.coef_, 'an', lin_model.intercept_) 

Coefficients:  [[0.55199162 1.96250928]] an [-0.0329537]


In [92]:
lin_model.coef_[0,0]

0.5519916163209287